Exircises for fp2 done
borman73/study pull request #3
Opened 2021-11-22 08:58 UTC by borman73

2021-11-22 12:22 UTC, Andrew8xx8 requested changes

2021-11-22 12:22 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        for item in self
`each` нужно реальзовать используя рекурсию

2021-11-22 12:22 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        for item in new_array
`reduce` нужно реализовать используя рекурсию

2021-11-22 15:03 UTC, borman73 commented
переделал

2021-11-23 17:14 UTC, borman73 commented on test/exercise/fp2/solution.rb
> +        for item in new_array
Переделал

2021-11-30 10:35 UTC, Andrew8xx8 approved these changes

2021-11-30 10:44 UTC, merged